/**
 * Shared badge style maps and option lists for task status and priority.
 *
 * Used by the tasks list and task detail clients. Centralised so adding a new
 * status/priority only requires updating this file.
 *
 * Pure constants only — no imports — safe to import from both server and
 * client components.
 */

export const STATUS_COLORS: Record<string, string> = {
  pending: "bg-gray-100 text-gray-700 dark:bg-zinc-700 dark:text-zinc-300",
  planned: "bg-blue-100 text-blue-700 dark:bg-blue-900 dark:text-blue-300",
  "in-progress": "bg-yellow-100 text-yellow-700 dark:bg-yellow-900 dark:text-yellow-300",
  done: "bg-green-100 text-green-700 dark:bg-green-900 dark:text-green-300",
  blocked: "bg-red-100 text-red-700 dark:bg-red-900 dark:text-red-300",
  "pending-triage": "bg-purple-100 text-purple-700 dark:bg-purple-900 dark:text-purple-300",
  wontdo: "bg-gray-200 text-gray-500 dark:bg-zinc-800 dark:text-zinc-500 line-through",
};

export const PRIORITY_COLORS: Record<string, string> = {
  P0: "bg-red-600 text-white dark:bg-red-700",
  P1: "bg-orange-500 text-white dark:bg-orange-700",
  P2: "bg-gray-200 text-gray-700 dark:bg-zinc-600 dark:text-zinc-200",
};

/**
 * Author of a task — derived from the existing `section` field.
 *
 * `"ceo"` items come from the POST /tasks route which always inserts into the
 * `## CEO Requests` section, so they originated from the user via the UI.
 * Everything else (`"discovered"`, `"triaged"`, `"wontdo"`) was generated by
 * the autonomous CTO agent and is therefore "Created by RedEye".
 *
 * Deriving at render time avoids a parser/types/UI lockstep update and keeps
 * tasks.md backward-compatible. See spec docs/specs/T134-task-author.md (AD-1).
 */
export type TaskAuthor = "user" | "redeye";

export function taskAuthor(section: string | undefined): TaskAuthor {
  return section === "ceo" ? "user" : "redeye";
}

export const AUTHOR_BADGE_STYLES: Record<
  TaskAuthor,
  { label: string; className: string }
> = {
  user: {
    label: "Created by User",
    className:
      "bg-blue-50 text-blue-700 dark:bg-blue-950/30 dark:text-blue-300",
  },
  redeye: {
    label: "Created by RedEye",
    className:
      "bg-violet-50 text-violet-700 dark:bg-violet-950/30 dark:text-violet-300",
  },
};

export const STATUS_OPTIONS = [
  "pending",
  "planned",
  "in-progress",
  "done",
  "blocked",
  "pending-triage",
  "wontdo",
];

export const PRIORITY_OPTIONS = ["P0", "P1", "P2"];
